landing/urls.py
from django.urls import path
from landing.views import Index

urlpatterns = [
    path('', Index.as_view(), name="index"),
]

omelette/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('accounts/', include('allauth.urls')),
    path('social/', include('social.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.urls import path
from .views import ProfileEditView, ProfileView, People

urlpatterns = [
    path('profile/<int:pk>', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>', ProfileEditView.as_view(), name='profile-edit'),
    path('people', People.as_view(), name='people'),
]

landing/models.py
from django.db import models

# Create your models here.

social/models.py
from asyncio.windows_events import NULL
from hashlib import blake2b
from pickle import TRUE
from ssl import create_default_context
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

GENDERS = (
    ('m', 'male'),
    ('f', 'female'),
    ('nb', 'non binary')
)

SEXUALITY = (
    ('w', 'like women'),
    ('m', 'like men'),
    ('bi', 'like both')
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True, verbose_name='user', related_name='profile', on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, default="hey")
    physical_desc = models.CharField(max_length=500, default="georgeous")
    birthdate = models.DateField(null=True, blank=True)
    age = models.CharField(max_length=5)
    gender = models.CharField(choices=GENDERS, max_length=20)
    sexuality = models.CharField(choices=SEXUALITY, max_length=20, default='bi')
    img1 = models.ImageField(upload_to='profile_pictures', default='profile_pictures/default.jpg')
    img2 = models.ImageField(upload_to='profile_pictures', default='profile_pictures/default.jpg')
    img3 = models.ImageField(upload_to='profile_pictures', default='profile_pictures/default.jpg')
    img4 = models.ImageField(upload_to='profile_pictures', default='profile_pictures/default.jpg')
    likers = models.ManyToManyField(User, blank=True, related_name='likers')
    liked = models.ManyToManyField(User, blank=True, related_name='liked')

    def find_age(self):
        import datetime
        self.age = (datetime.date.today() - self.birthdate)/365

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, created, **kwargs):
    instance.profile.save()

landing/views.py
from django.shortcuts import render
from django.views import View

# Create your views here.

class Index(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'landing/index.html')


social/views.py
from audioop import reverse
from xml.etree.ElementTree import Comment
from django.shortcuts import render, redirect
from django.db.models import Q
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.views import View
from .models import UserProfile
from django.views.generic.edit import UpdateView, DeleteView


# Create your views here.
class ProfileView(View):
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        user = profile.user
        likers = profile.likers.all()
        liked = profile.liked.all()

        context = {
            'user': user,
            'profile': profile,
            'likers': likers,
            'liked': liked,
        }

        return render(request, 'social/profile.html', context)

class ProfileEditView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = UserProfile
    fields = ['bio', 'physical_desc', 'birthdate', 'gender', 'sexuality', 'img1', 'img2', 'img3','img4']
    template_name = 'social/profile_edit.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('profile', kwargs={'pk': pk})

    def test_func(self):
        profile = self.get_object()
        return self.request.user == profile.user
    
class People(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'social/people.html')

landing/templates/landing/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">

    <script src="{% static 'script.js' %}"></script>
    
    <title>omelove</title>
  </head>
  <body>
    {% include 'landing/navbar.html' %}
    {% block content %}
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

landing/templates/landing/index.html
{% extends 'landing/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mt-5">
        <div class="col-md-10 col-sm-12 text-center">
            <img class="img-responsive" src="{% static 'images/girlface2.jpg' %}">
            <h1 class="display-2">welcome!</h1>
            <p class="mt-3 lead">if you're here, that means you're extremely single and desperate. but never fear, omelette is here!</p>
            <p class="mt-3 lead">cette application vous permettra de rencontrer des gens en recherche d'amour à Rochambeau. </p>
            {% if user.is_authenticated %}
            <div class="d-flex justify-content-center mt-5">
                <a href="{% url 'people' %}" class="btn btn-dark">start dating!</a> 
            </div>
            {% else %}
            <div class="d-flex justify-content-center mt-5">
                <a href="{% url 'account_login' %}" class="btn btn-light mr-2">log in</a> 
                <br>
                <a href="{% url 'account_signup' %}" class="btn btn-dark">register</a>
            </div>
            {% endif %}
        </div>
    </div>
</div>
<footer class="footer mt-auto py-3 fixed-bottom justify-content-center" style="background-color:  #d99679;">
    <div class="container">
        <span class="text-muted justify-content-center"> enjoying this app? why don't you support the developer at <a href="https://sunnysidestudio.webflow.io/">sunnysidestudios.com</a></span>
    </div>
</footer>
{% endblock content %}

landing/templates/landing/navbar.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <a class="navbar-brand" 
          {% if user.is_authenticated %}
          href="{% url 'index' %}"
          {% else %}
          href="{% url 'index' %}"
          {% endif %}>
          <img classs="img-responsive" width="" height="50px" src="{% static 'images/icon.jpg' %}">
          omelette</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            </ul>
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
              <a class="nav-item dropdown-toggle text-dark" data-bs-toggle="dropdown" role="button" aria-expanded="false"><i class="fas fa-user"></i></a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'profile' user.profile.pk %}">profile</a></li>
                <li><a class="dropdown-item" href="{% url 'people' %}">people</a></li>
                <li><a class="dropdown-item" href="#">my matches</a></li>
                <li><a class="dropdown-item" href="{% url 'account_logout' %}">sign out</a></li>
              </ul>
            </div>
            {% endif %}
          </div>
        </div>
      </nav>
    </div>


social/templates/social/people.html
{% extends 'landing/base.html' %}
{% load static %}

{% block content %}
<div class="countdown people-body" id="js-countdown">

  <div class="countdown__item countdown__item--large">
    <div class="countdown__timer js-countdown-days" id="days">
      
    </div>
    
    <div class="countdown__label" id="day-countdown">Days until launch</div>
  </div>
  
  <div class="countdown__item">
    <div class="countdown__timer js-countdown-hours" id="hours">
      
    </div>
    
    <div class="countdown__label" id="hour-countdown">Hours</div>
  </div>
  
  <div class="countdown__item">
    <div class="countdown__timer js-countdown-minutes" id="minutes">
      
    </div>
    
    <div class="countdown__label" id="minute-countdown">Minutes</div>
  </div>
  
  <div class="countdown__item">
    <div class="countdown__timer js-countdown-seconds" id="seconds">
      
    </div>
    
    <div class="countdown__label" id="second-countdown">Seconds</div>
  </div>

  <p style="text-transform: lowercase; font-size: 0.5em;">if you want this page to become available as soon as possible, make sure to share with your friends. <br> or, you can buy me a starbucks as motivation. your choice. </p>
</div>
{% endblock content %}

social/templates/social/profile.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<!-- <div class="container">
    <div class="row mt-5">
        <div class="col-sm-6 justify-content-center ">
            <img src="{{ profile.img1.url }}" class="img-thumbnail" width="100px" height="100px">
        </div>
        <div class="col-sm-6">
            <img src="{{ profile.img2.url }}" class="img-thumbnail" width="100px" height="100px">
        </div>
        <div class="col-md-3 col-sm-6">
            <a href="{% url 'profile-edit' user.profile.pk %}" class="btn btn-light">back to feed</a>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="card shadow-sm col-md-8 col-sm-12 border-bottom px-5 pt-3"> 
        </div>
    </div>
</div> -->
<section class="h-100 gradient-custom-2">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-lg-9 col-xl-7">
          <div class="card">
            <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
              <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                <a href="{% url 'profile-edit' profile.pk %}"><button type="button" class="btn btn-outline-light" data-mdb-ripple-color="dark"
                  style="z-index: 1;">
                  Edit profile
                </button></a>
              </div>
            </div>
            <div class="p-4 text-black" style="background-color: #f8f9fa;">
              <div class="d-flex justify-content-end text-center py-1">
                <div>
                  <p class="mb-1 h5">{{ profile.get_gender_display }}</p>
                  <p class="small text-muted mb-0">gender</p>
                </div>
                <div class="px-3">
                  <p class="mb-1 h5">{{ profile.get_sexuality_display }}</p>
                  <p class="small text-muted mb-0">sexuality</p>
                </div>
                <div>
                  <p class="mb-1 h5">{{ profile.birthdate|timesince }}</p>
                  <p class="small text-muted mb-0">age</p>
                </div>
              </div>
            </div>
            <div class="card-body p-4 text-black">
              <div class="mb-5">
                <p class="lead fw-normal mb-1">bio</p>
                <div class="p-4" style="background-color: #f8f9fa;">
                  <p class="font-italic mb-1">{{ profile.bio }}</p>
                </div>
              </div>
              <div class="mb-5">
                <p class="lead fw-normal mb-1">appearance</p>
                <div class="p-4" style="background-color: #f8f9fa;">
                  <p class="font-italic mb-1">{{ profile.physical_desc }}</p>
                </div>
              </div>
              <div class="d-flex justify-content-between align-items-center mb-4">
                <p class="lead fw-normal mb-0">photos</p>
              </div>
              <div class="row g-2">
                <div class="col mb-2">
                  <img src="{{ profile.img1.url }}"
                    alt="image 1" class="w-100 rounded-3">
                </div>
                <div class="col mb-2">
                  <img src="{{ profile.img2.url }}"
                    alt="image 1" class="w-100 rounded-3">
                </div>
              </div>
              <div class="row g-2">
                <div class="col">
                  <img src="{{ profile.img3.url }}"
                    alt="image 1" class="w-100 rounded-3">
                </div>
                <div class="col">
                  <img src="{{ profile.img4.url }}"
                    alt="image 1" class="w-100 rounded-3">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

social/templates/social/profile_edit.html
{% extends 'landing/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-5 col-sm-6">
            <a href="{% url 'profile' object.pk %}" class="btn btn-light">back to profile</a>
        </div>
    </div>
    <div class="row justify-content-center mt-3">
        <div class="col-md-5 col-sm-12 border-bottom">
            <h5>update your profile</h5>
        </div>
    </div>
    <div class="row justify-content-center mt-3 mb-5">
        <div class="col-md-5 col-sm-12 border-bottom">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <div class="d-grid gap-2">
                    <button class="btn btn-success mt-3">submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
    {% load static %}
      
     <!-- Font Awesome -->
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
     <!-- Google Fonts -->
     <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
     <!-- Bootstrap core CSS -->
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'style.css' %}">
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div class="row justify-content-center pt-3">
      <div class="col-md-6">
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">{{message}}</div>
        {% endfor %}
    </div>
    </div>
    {% endif %}
    <div class="mt-5">
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>
</html>